import {
  app,
  BrowserWindow,
  ipcMain,
  shell,
  protocol,
  net,
  Tray,
  Menu,
  nativeImage,
  Notification,
  dialog,
  globalShortcut,
} from 'electron';
import path from 'node:path';
import fs from 'node:fs';
import { pathToFileURL } from 'node:url';
import { initDb, kvLoadAll, kvSetRaw, kvDelete, kvReset, closeDb } from './db';
import { initAutoUpdater } from './updater';
import { initNotificationScheduler, getTraySummary } from './scheduler';
import {
  setCredentials as pluggySetCredentials,
  clearCredentials as pluggyClearCredentials,
  hasCredentials as pluggyHasCredentials,
  testCredentials as pluggyTestCredentials,
  createConnectToken as pluggyConnectToken,
  getItem as pluggyGetItem,
  refreshItem as pluggyRefreshItem,
  deleteItem as pluggyDeleteItem,
  listAccounts as pluggyListAccounts,
  listTransactions as pluggyListTransactions,
  setAppSession as pluggySetAppSession,
  clearAppSession as pluggyClearAppSession,
  getAppSessionInfo as pluggyGetAppSessionInfo,
  testAppSession as pluggyTestAppSession,
  listItems as pluggyListItems,
} from './pluggy';

const isDev = !app.isPackaged || process.env.ELECTRON_DEV === '1';
const startedHidden = process.argv.includes('--hidden');

let mainWindow: BrowserWindow | null = null;
let tray: Tray | null = null;
let quitting = false;

// Single instance lock — if another instance launches, focus the existing one.
const gotLock = app.requestSingleInstanceLock();
if (!gotLock) {
  app.quit();
}

app.on('second-instance', () => {
  if (mainWindow) {
    if (mainWindow.isMinimized()) mainWindow.restore();
    if (!mainWindow.isVisible()) mainWindow.show();
    mainWindow.focus();
  }
});

// Register custom protocol so the bundled Next.js export loads with absolute
// asset paths. Must be called before app ready.
protocol.registerSchemesAsPrivileged([
  {
    scheme: 'app',
    privileges: {
      standard: true,
      secure: true,
      supportFetchAPI: true,
      stream: true,
    },
  },
]);

function resolveStaticPath(urlPath: string): string {
  const outDir = path.join(__dirname, '..', 'out');
  let p = decodeURIComponent(urlPath);
  if (p.endsWith('/')) p = p + 'index.html';
  if (!path.extname(p)) p = p + '/index.html';
  const resolved = path.join(outDir, p);
  // Stop directory traversal.
  if (!resolved.startsWith(outDir)) return path.join(outDir, 'index.html');
  return resolved;
}

function getAppIconPath(): string {
  // build/icon.ico is generated by scripts/build-icon.mjs and packed into
  // the asar at production time. In dev it sits in the repo root/build.
  return path.join(__dirname, '..', 'build', 'icon.ico');
}

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 480,
    height: 880,
    minWidth: 380,
    minHeight: 600,
    backgroundColor: '#15171b',
    autoHideMenuBar: true,
    title: 'Financas',
    icon: getAppIconPath(),
    show: !startedHidden,
    frame: false,
    resizable: true,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
    },
  });

  // Notify the renderer when maximize state changes so the title bar can
  // swap its maximize/restore icon.
  mainWindow.on('maximize', () => {
    mainWindow?.webContents.send('window:maximizedChange', true);
  });
  mainWindow.on('unmaximize', () => {
    mainWindow?.webContents.send('window:maximizedChange', false);
  });

  if (isDev) {
    mainWindow.loadURL('http://localhost:3000');
    mainWindow.webContents.openDevTools({ mode: 'detach' });
  } else {
    mainWindow.loadURL('app://./');
  }

  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url);
    return { action: 'deny' };
  });

  // Hide to tray on close instead of quitting, so the app keeps running.
  mainWindow.on('close', (e) => {
    if (!quitting) {
      e.preventDefault();
      mainWindow?.hide();
    }
  });
}

function fmtBRL(value: number): string {
  return value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
}

function rebuildTrayMenu() {
  if (!tray) return;
  const summary = getTraySummary();
  const summaryLabel =
    summary.count === 0
      ? 'Nada vencendo nos próximos 7 dias'
      : `${summary.count} conta${summary.count === 1 ? '' : 's'} a vencer · ${fmtBRL(summary.total)}`;

  const menu = Menu.buildFromTemplate([
    { label: summaryLabel, enabled: false },
    { type: 'separator' },
    {
      label: 'Abrir Financas',
      click: () => activateForUrl('/home/'),
    },
    {
      label: 'Adicionar despesa rápida',
      click: () => activateForUrl('/debts/?new=1'),
    },
    {
      label: 'Adicionar receita',
      click: () => activateForUrl('/home/?income=1'),
    },
    { type: 'separator' },
    {
      label: 'Sair',
      click: () => {
        quitting = true;
        app.quit();
      },
    },
  ]);
  tray.setContextMenu(menu);
  tray.setToolTip(`Financas · ${summaryLabel}`);
}

function createTray() {
  const iconPath = getAppIconPath();
  const fallback = nativeImage.createEmpty();
  let image = nativeImage.createFromPath(iconPath);
  if (image.isEmpty()) image = fallback;

  tray = new Tray(image);
  rebuildTrayMenu();
  // Refresh every 5 min so the summary stays current without the renderer
  // having to push updates.
  setInterval(rebuildTrayMenu, 5 * 60 * 1000);
  tray.on('click', () => {
    if (!mainWindow) {
      createWindow();
      return;
    }
    if (mainWindow.isVisible()) mainWindow.hide();
    else {
      mainWindow.show();
      mainWindow.focus();
    }
    rebuildTrayMenu();
  });
}

// Settings used both when *writing* the login item and when *reading* it
// back. On Windows, getLoginItemSettings without these args checks a
// different registry key than the one setLoginItemSettings creates, so
// you must pass the same path/args to both calls.
function getLoginItemOpts(): { path: string; args: string[] } {
  return {
    path: app.getPath('exe'),
    args: ['--hidden'],
  };
}

function getAutoStartState(): boolean {
  if (process.platform !== 'win32') {
    return app.getLoginItemSettings().openAtLogin;
  }
  return app.getLoginItemSettings(getLoginItemOpts()).openAtLogin;
}

function registerIpc() {
  // Renderer calls these via the preload bridge. KV operations are the
  // backbone of the app's storage layer.
  ipcMain.on('kv:loadAllSync', (e) => {
    e.returnValue = kvLoadAll();
  });

  ipcMain.on('kv:set', (_e, key: string, rawValue: string) => {
    try {
      kvSetRaw(key, rawValue);
    } catch (err) {
      console.error('kv:set failed', key, err);
    }
  });

  ipcMain.on('kv:delete', (_e, key: string) => {
    try {
      kvDelete(key);
    } catch (err) {
      console.error('kv:delete failed', key, err);
    }
  });

  ipcMain.handle('kv:reset', () => {
    kvReset();
    return true;
  });

  ipcMain.handle('app:getAutoStart', () => getAutoStartState());
  ipcMain.handle('app:setAutoStart', (_e, enabled: boolean) => {
    if (process.platform === 'win32') {
      app.setLoginItemSettings({
        openAtLogin: enabled,
        ...getLoginItemOpts(),
      });
    }
    return getAutoStartState();
  });

  ipcMain.handle('app:quit', () => {
    quitting = true;
    app.quit();
  });

  ipcMain.handle('app:openExternal', (_e, url: string) => shell.openExternal(url));

  // Folder picker for local backups (4.2). Renderer triggers a JSON save
  // there; main writes the file with native fs to skip Chromium's download
  // prompt.
  ipcMain.handle('backup:chooseFolder', async () => {
    const result = await dialog.showOpenDialog({
      title: 'Escolha a pasta de backup',
      properties: ['openDirectory', 'createDirectory'],
    });
    if (result.canceled || result.filePaths.length === 0) return null;
    return result.filePaths[0];
  });

  ipcMain.handle(
    'backup:writeJson',
    (_e, payload: { folder: string; json: string }) => {
      try {
        if (!fs.existsSync(payload.folder)) {
          fs.mkdirSync(payload.folder, { recursive: true });
        }
        const ts = new Date().toISOString().split('T')[0];
        const file = path.join(payload.folder, `financas-backup-${ts}.json`);
        fs.writeFileSync(file, payload.json, 'utf8');
        // Keep last 30: walk the folder, sort, delete the rest.
        const files = fs
          .readdirSync(payload.folder)
          .filter((f) => f.startsWith('financas-backup-') && f.endsWith('.json'))
          .sort();
        if (files.length > 30) {
          for (const old of files.slice(0, files.length - 30)) {
            try {
              fs.unlinkSync(path.join(payload.folder, old));
            } catch {
              /* best-effort */
            }
          }
        }
        return file;
      } catch (err) {
        console.error('backup:writeJson failed', err);
        return null;
      }
    }
  );

  ipcMain.handle('tray:getSummary', () => getTraySummary());

  // ── Pluggy / Open Finance ──────────────────────────────────────────
  ipcMain.handle('pluggy:hasCredentials', () => pluggyHasCredentials());
  ipcMain.handle(
    'pluggy:setCredentials',
    (_e, creds: { clientId: string; clientSecret: string }) => {
      pluggySetCredentials(creds);
      return true;
    }
  );
  ipcMain.handle('pluggy:clearCredentials', () => {
    pluggyClearCredentials();
    return true;
  });
  ipcMain.handle('pluggy:testCredentials', async () => pluggyTestCredentials());
  ipcMain.handle('pluggy:connectToken', async (_e, itemId?: string) =>
    pluggyConnectToken(itemId)
  );
  ipcMain.handle('pluggy:getItem', async (_e, itemId: string) => pluggyGetItem(itemId));
  ipcMain.handle('pluggy:refreshItem', async (_e, itemId: string) =>
    pluggyRefreshItem(itemId)
  );
  ipcMain.handle('pluggy:deleteItem', async (_e, itemId: string) => {
    await pluggyDeleteItem(itemId);
    return true;
  });
  ipcMain.handle('pluggy:listAccounts', async (_e, itemId: string) =>
    pluggyListAccounts(itemId)
  );
  ipcMain.handle(
    'pluggy:listTransactions',
    async (_e, accountId: string, options?: { from?: string; to?: string }) =>
      pluggyListTransactions(accountId, options)
  );

  // App-session mode (dashboard JWT)
  ipcMain.handle('pluggy:setAppSession', (_e, token: string) => {
    pluggySetAppSession(token);
    return true;
  });
  ipcMain.handle('pluggy:clearAppSession', () => {
    pluggyClearAppSession();
    return true;
  });
  ipcMain.handle('pluggy:getAppSessionInfo', () => pluggyGetAppSessionInfo());
  ipcMain.handle('pluggy:testAppSession', async () => pluggyTestAppSession());
  ipcMain.handle('pluggy:listItems', async () => pluggyListItems());

  /**
   * One-click connect flow. Opens an Electron BrowserWindow at the
   * Pluggy dashboard, lets the user authenticate (Auth0 redirect chain
   * works because cookies persist on the dedicated session partition),
   * then sniffs the first request that goes out to my-api.pluggy.ai to
   * extract the Bearer token. Saves it as the app session and closes
   * the window.
   *
   * No credential ever passes through our renderer — it's only seen by
   * the dashboard's own JS inside its window, then captured at the
   * webRequest layer in main.
   */
  ipcMain.handle('pluggy:loginFlow', async () => {
    return new Promise<{ ok: boolean; message?: string }>((resolve) => {
      const win = new BrowserWindow({
        width: 1024,
        height: 760,
        title: 'Pluggy · login',
        parent: mainWindow ?? undefined,
        modal: false,
        backgroundColor: '#15171b',
        autoHideMenuBar: true,
        webPreferences: {
          // Dedicated partition so cookies persist between flows but
          // don't pollute the main app's session.
          partition: 'persist:pluggy-login',
          contextIsolation: true,
          nodeIntegration: false,
          sandbox: true,
        },
      });

      let captured = false;
      const filter = { urls: ['*://my-api.pluggy.ai/*'] };

      win.webContents.session.webRequest.onBeforeSendHeaders(
        filter,
        (details, callback) => {
          // Headers come keyed in a way that varies — accept either case.
          const rawAuth =
            details.requestHeaders['Authorization'] ??
            details.requestHeaders['authorization'];
          if (
            !captured &&
            typeof rawAuth === 'string' &&
            rawAuth.startsWith('Bearer ')
          ) {
            captured = true;
            pluggySetAppSession(rawAuth.slice(7));
            // Close shortly after so the in-flight request still completes.
            setTimeout(() => {
              if (!win.isDestroyed()) win.close();
            }, 300);
            resolve({ ok: true });
          }
          callback({ requestHeaders: details.requestHeaders });
        }
      );

      // 5min hard cap so a stalled login doesn't leave the window
      // floating forever.
      const timer = setTimeout(
        () => {
          if (!captured && !win.isDestroyed()) {
            win.close();
            resolve({ ok: false, message: 'Tempo esgotado (5 minutos)' });
          }
        },
        5 * 60 * 1000
      );

      win.on('closed', () => {
        clearTimeout(timer);
        if (!captured) {
          resolve({ ok: false, message: 'Janela fechada antes do login' });
        }
      });

      win.loadURL('https://meu.pluggy.ai/cash');
    });
  });

  // Frameless window controls — replace the native title bar buttons.
  ipcMain.handle('window:minimize', () => {
    mainWindow?.minimize();
  });

  ipcMain.handle('window:toggleMaximize', () => {
    if (!mainWindow) return false;
    if (mainWindow.isMaximized()) {
      mainWindow.unmaximize();
      return false;
    }
    mainWindow.maximize();
    return true;
  });

  ipcMain.handle('window:close', () => {
    // Goes through our own 'close' handler that hides to tray instead of quitting.
    mainWindow?.close();
  });

  ipcMain.handle('window:isMaximized', () => mainWindow?.isMaximized() ?? false);

  // Legacy fallback: renderer can still request a toast (e.g. for one-off
  // notifications outside the scheduler). The main-process scheduler is
  // now the primary path for due-bill toasts.
  ipcMain.handle(
    'notify:show',
    (_e, payload: { title: string; body: string; tag?: string; targetUrl?: string }) => {
      if (!Notification.isSupported()) return false;
      const n = new Notification({
        title: payload.title,
        body: payload.body,
        icon: getAppIconPath(),
        silent: false,
      });
      n.on('click', () => activateForUrl(payload.targetUrl ?? '/'));
      n.show();
      return true;
    }
  );
}

function activateForUrl(targetUrl: string): void {
  if (!mainWindow) {
    createWindow();
    // createWindow reassigns the module-level mainWindow; re-grab it here
    // so TS sees the new value and we can safely subscribe to load events.
    const win = mainWindow as BrowserWindow | null;
    if (!win) return;
    win.webContents.once('did-finish-load', () => {
      win.webContents.send('nav:to', targetUrl);
    });
    return;
  }
  if (mainWindow.isMinimized()) mainWindow.restore();
  mainWindow.show();
  mainWindow.focus();
  mainWindow.webContents.send('nav:to', targetUrl);
}

app.whenReady().then(() => {
  // Windows uses this to attribute toast notifications to our app — without
  // it the Action Center shows "electron.app.Financas" and clicks won't
  // re-launch the right shortcut.
  if (process.platform === 'win32') {
    app.setAppUserModelId('com.financas.desktop');
  }

  initDb();
  registerIpc();

  protocol.handle('app', async (req) => {
    const url = new URL(req.url);
    const filePath = resolveStaticPath(url.pathname);
    return net.fetch(pathToFileURL(filePath).toString());
  });

  createWindow();
  createTray();

  initAutoUpdater({
    getMainWindow: () => mainWindow,
    iconPath: getAppIconPath(),
  });

  initNotificationScheduler({
    iconPath: getAppIconPath(),
    onActivate: (url) => activateForUrl(url),
  });

  // Global hotkey: Ctrl+Shift+F brings Financas to the foreground from any
  // app. Fails silently if the combo is already taken — user can disable
  // it via the OS if it conflicts.
  try {
    globalShortcut.register('CommandOrControl+Shift+F', () => {
      if (!mainWindow) {
        createWindow();
        return;
      }
      if (mainWindow.isVisible() && mainWindow.isFocused()) {
        mainWindow.hide();
      } else {
        if (mainWindow.isMinimized()) mainWindow.restore();
        mainWindow.show();
        mainWindow.focus();
      }
    });
  } catch (err) {
    console.error('globalShortcut register failed', err);
  }

  // Windows jump list — quick actions from the taskbar icon's right-click.
  if (process.platform === 'win32') {
    try {
      app.setUserTasks([
        {
          program: process.execPath,
          arguments: '--nav=/debts/?new=1',
          title: 'Nova despesa',
          description: 'Adicionar uma conta nova',
          iconPath: process.execPath,
          iconIndex: 0,
        },
        {
          program: process.execPath,
          arguments: '--nav=/home/?income=1',
          title: 'Nova receita',
          description: 'Lançar entrada manual',
          iconPath: process.execPath,
          iconIndex: 0,
        },
      ]);
    } catch (err) {
      console.error('setUserTasks failed', err);
    }
  }

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on('before-quit', () => {
  quitting = true;
});

app.on('window-all-closed', () => {
  // Keep app running in tray on Windows/Linux. Only quit on macOS standard.
  if (process.platform === 'darwin') app.quit();
});

app.on('will-quit', () => {
  globalShortcut.unregisterAll();
  closeDb();
});
