import { app, BrowserWindow, ipcMain, shell, protocol, net, Tray, Menu, nativeImage } from 'electron';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { initDb, kvLoadAll, kvSetRaw, kvDelete, kvReset, closeDb } from './db';

const isDev = !app.isPackaged || process.env.ELECTRON_DEV === '1';
const startedHidden = process.argv.includes('--hidden');

let mainWindow: BrowserWindow | null = null;
let tray: Tray | null = null;
let quitting = false;

// Single instance lock — if another instance launches, focus the existing one.
const gotLock = app.requestSingleInstanceLock();
if (!gotLock) {
  app.quit();
}

app.on('second-instance', () => {
  if (mainWindow) {
    if (mainWindow.isMinimized()) mainWindow.restore();
    if (!mainWindow.isVisible()) mainWindow.show();
    mainWindow.focus();
  }
});

// Register custom protocol so the bundled Next.js export loads with absolute
// asset paths. Must be called before app ready.
protocol.registerSchemesAsPrivileged([
  {
    scheme: 'app',
    privileges: {
      standard: true,
      secure: true,
      supportFetchAPI: true,
      stream: true,
    },
  },
]);

function resolveStaticPath(urlPath: string): string {
  const outDir = path.join(__dirname, '..', 'out');
  let p = decodeURIComponent(urlPath);
  if (p.endsWith('/')) p = p + 'index.html';
  if (!path.extname(p)) p = p + '/index.html';
  const resolved = path.join(outDir, p);
  // Stop directory traversal.
  if (!resolved.startsWith(outDir)) return path.join(outDir, 'index.html');
  return resolved;
}

function getAppIconPath(): string {
  // build/icon.ico is generated by scripts/build-icon.mjs and packed into
  // the asar at production time. In dev it sits in the repo root/build.
  return path.join(__dirname, '..', 'build', 'icon.ico');
}

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 480,
    height: 880,
    minWidth: 380,
    minHeight: 600,
    backgroundColor: '#15171b',
    autoHideMenuBar: true,
    title: 'Financas',
    icon: getAppIconPath(),
    show: !startedHidden,
    frame: false,
    resizable: true,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
    },
  });

  // Notify the renderer when maximize state changes so the title bar can
  // swap its maximize/restore icon.
  mainWindow.on('maximize', () => {
    mainWindow?.webContents.send('window:maximizedChange', true);
  });
  mainWindow.on('unmaximize', () => {
    mainWindow?.webContents.send('window:maximizedChange', false);
  });

  if (isDev) {
    mainWindow.loadURL('http://localhost:3000');
    mainWindow.webContents.openDevTools({ mode: 'detach' });
  } else {
    mainWindow.loadURL('app://./');
  }

  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url);
    return { action: 'deny' };
  });

  // Hide to tray on close instead of quitting, so the app keeps running.
  mainWindow.on('close', (e) => {
    if (!quitting) {
      e.preventDefault();
      mainWindow?.hide();
    }
  });
}

function createTray() {
  const iconPath = getAppIconPath();
  const fallback = nativeImage.createEmpty();
  let image = nativeImage.createFromPath(iconPath);
  if (image.isEmpty()) image = fallback;

  tray = new Tray(image);
  tray.setToolTip('Financas');

  const menu = Menu.buildFromTemplate([
    {
      label: 'Abrir',
      click: () => {
        if (!mainWindow) createWindow();
        else {
          if (mainWindow.isMinimized()) mainWindow.restore();
          mainWindow.show();
          mainWindow.focus();
        }
      },
    },
    { type: 'separator' },
    {
      label: 'Sair',
      click: () => {
        quitting = true;
        app.quit();
      },
    },
  ]);
  tray.setContextMenu(menu);
  tray.on('click', () => {
    if (!mainWindow) {
      createWindow();
      return;
    }
    if (mainWindow.isVisible()) mainWindow.hide();
    else {
      mainWindow.show();
      mainWindow.focus();
    }
  });
}

// Settings used both when *writing* the login item and when *reading* it
// back. On Windows, getLoginItemSettings without these args checks a
// different registry key than the one setLoginItemSettings creates, so
// you must pass the same path/args to both calls.
function getLoginItemOpts(): { path: string; args: string[] } {
  return {
    path: app.getPath('exe'),
    args: ['--hidden'],
  };
}

function getAutoStartState(): boolean {
  if (process.platform !== 'win32') {
    return app.getLoginItemSettings().openAtLogin;
  }
  return app.getLoginItemSettings(getLoginItemOpts()).openAtLogin;
}

function registerIpc() {
  // Renderer calls these via the preload bridge. KV operations are the
  // backbone of the app's storage layer.
  ipcMain.on('kv:loadAllSync', (e) => {
    e.returnValue = kvLoadAll();
  });

  ipcMain.on('kv:set', (_e, key: string, rawValue: string) => {
    try {
      kvSetRaw(key, rawValue);
    } catch (err) {
      console.error('kv:set failed', key, err);
    }
  });

  ipcMain.on('kv:delete', (_e, key: string) => {
    try {
      kvDelete(key);
    } catch (err) {
      console.error('kv:delete failed', key, err);
    }
  });

  ipcMain.handle('kv:reset', () => {
    kvReset();
    return true;
  });

  ipcMain.handle('app:getAutoStart', () => getAutoStartState());
  ipcMain.handle('app:setAutoStart', (_e, enabled: boolean) => {
    if (process.platform === 'win32') {
      app.setLoginItemSettings({
        openAtLogin: enabled,
        ...getLoginItemOpts(),
      });
    }
    return getAutoStartState();
  });

  ipcMain.handle('app:quit', () => {
    quitting = true;
    app.quit();
  });

  ipcMain.handle('app:openExternal', (_e, url: string) => shell.openExternal(url));

  // Frameless window controls — replace the native title bar buttons.
  ipcMain.handle('window:minimize', () => {
    mainWindow?.minimize();
  });

  ipcMain.handle('window:toggleMaximize', () => {
    if (!mainWindow) return false;
    if (mainWindow.isMaximized()) {
      mainWindow.unmaximize();
      return false;
    }
    mainWindow.maximize();
    return true;
  });

  ipcMain.handle('window:close', () => {
    // Goes through our own 'close' handler that hides to tray instead of quitting.
    mainWindow?.close();
  });

  ipcMain.handle('window:isMaximized', () => mainWindow?.isMaximized() ?? false);
}

app.whenReady().then(() => {
  initDb();
  registerIpc();

  protocol.handle('app', async (req) => {
    const url = new URL(req.url);
    const filePath = resolveStaticPath(url.pathname);
    return net.fetch(pathToFileURL(filePath).toString());
  });

  createWindow();
  createTray();

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on('before-quit', () => {
  quitting = true;
});

app.on('window-all-closed', () => {
  // Keep app running in tray on Windows/Linux. Only quit on macOS standard.
  if (process.platform === 'darwin') app.quit();
});

app.on('will-quit', () => {
  closeDb();
});
