export interface User {
  salary: number;
  currentBalance: number;
  monthlyBudget: number;
}

export interface Entity {
  id: string;
  name: string;
  hue?: number;
  /** Optional emoji used as the entity glyph instead of the first letter. */
  icon?: string;
  createdAt: string;
}

export interface Debt {
  id: string;
  accountName: string;
  installmentValue: number;
  numberOfInstallments: number; // 0 = recurring
  dueDay: number;
  startMonth: number;
  startYear: number;
  entityIds: string[];
  entityNames: string[];
  isRecurring: boolean;
  createdAt: string;
}

export interface Installment {
  id: string;
  debtId: string;
  installmentNumber: number;
  dueDate: string;
  isPaid: boolean;
  paidAt: string | null;
  createdAt: string;
}

export interface Budget {
  id: string;
  month: number;
  year: number;
  totalIncome: number;
  totalExpenses: number;
  remaining: number;
  createdAt: string;
}

export interface Goal {
  id: string;
  type: 'savings' | 'emergency' | 'debt-free' | 'custom';
  name: string;
  targetValue: number;
  currentValue: number;
  deadline: string;
  hue?: number;
  createdAt: string;
}

/** Account type — checking, savings, cash, credit card, or investment.
 * Credit cards track a *negative* current balance (the open invoice).
 * Investments are illiquid holdings (Tesouro, FIIs, CDB, ações) imported
 * from Pluggy's /investments endpoint — currentBalance is the current
 * market value. */
export type AccountType = 'checking' | 'savings' | 'cash' | 'credit_card' | 'investment';

export interface Account {
  id: string;
  name: string;
  type: AccountType;
  /** For checking/savings/cash: cash on hand. For credit_card: amount owed
   * on the current open invoice (stored as a *positive* number; display
   * code adds the minus sign). */
  currentBalance: number;
  hue?: number;
  /** Set true on the account created by the v1→v2 migration so SET_USER
   * with `currentBalance` keeps writing here for backward compat. */
  isPrimary?: boolean;
  archived?: boolean;
  // --- Credit-card only ---
  /** Day of month the invoice closes (1-28 for safety). */
  closingDay?: number;
  /** Day of month the invoice is due. */
  dueDay?: number;
  /** Total credit limit (R$). */
  creditLimit?: number;
  // --- Pluggy-imported accounts only ---
  /** Pluggy account id — used as dedup key on every sync. */
  sourcePluggyAccountId?: string;
  /** FK to the BankConnection this account belongs to. Lets us purge
   * accounts when the user disconnects a bank. */
  sourceConnectionId?: string;
  createdAt: string;
}

export type IncomeDirection = 'entrada' | 'saida';

export interface Income {
  id: string;
  description: string;
  amount: number;
  date: string; // YYYY-MM-DD
  direction: IncomeDirection;
  /** Set on Incomes auto-generated by a RecurringIncome template, so the
   * generator can skip months that already have a row. */
  sourceRecurringId?: string;
  /** Set on Incomes imported via the Pluggy Open Finance integration.
   * Used for dedup so the same transaction never gets imported twice. */
  sourcePluggyId?: string;
  /** Optional FK to a BankConnection — useful for tracing where a row
   * came from and for bulk-purging when a connection is removed. */
  sourceConnectionId?: string;
  /** Optional FK to an Account when the transaction came in tied to a
   * specific Pluggy account. */
  accountId?: string;
  createdAt: string;
}

/** A bank link mediated by Pluggy. We persist only the itemId + metadata
 * — credentials live in the user's bank, the Pluggy itemId is the handle
 * we use to fetch transactions on demand. */
export interface BankConnection {
  id: string;
  pluggyItemId: string;
  institutionName: string;
  institutionLogoUrl?: string;
  /** Connector id from Pluggy — used to re-render brand color. */
  connectorId?: number;
  status: 'ok' | 'login_in_progress' | 'updating' | 'error' | 'needs_action';
  statusDetail?: string;
  lastSyncAt?: string;
  /** Total Income rows ever materialized from this connection. Helps
   * the UI report "synced N transactions" without scanning. */
  totalImported?: number;
  hue?: number;
  createdAt: string;
}

export interface Transfer {
  id: string;
  fromAccountId: string;
  toAccountId: string;
  amount: number;
  date: string; // YYYY-MM-DD
  note?: string;
  createdAt: string;
}

/**
 * Template for incomes that repeat every month (salary, freelance retainer,
 * rent paid to you). The generator in FinanceContext fires on hydrate +
 * month-tick and materializes an Income row per active month.
 */
export interface RecurringIncome {
  id: string;
  name: string;
  amount: number;
  dueDay: number;
  isActive: boolean;
  startMonth: number;
  startYear: number;
  /** Last YYYY-MM the generator created an Income for. Helps dedup. */
  lastGeneratedMonth?: string;
  createdAt: string;
}

export type DebtStatus = 'atrasado' | 'breve' | 'ok' | 'pago';

export interface FinanceState {
  user: User;
  entities: Entity[];
  debts: Debt[];
  installments: Installment[];
  budgets: Budget[];
  goals: Goal[];
  incomes: Income[];
  /** Map of `${debtId}@${dueDate}` -> ISO until-date. Bill is hidden from
   * due-soon checks and notifications while now < snoozedUntil. */
  snoozes: Record<string, string>;
  /** Bank accounts / wallets / credit cards. Migrated from user.currentBalance
   * on first run — see ensureAccountsMigration in FinanceContext. */
  accounts: Account[];
  /** Templates that auto-generate monthly Income rows. */
  recurringIncomes: RecurringIncome[];
  /** Transfers between accounts. Not counted as income/expense in stats. */
  transfers: Transfer[];
  /** Open Finance bank links via Pluggy. */
  bankConnections: BankConnection[];
  isHydrated: boolean;
}

export type FinanceAction =
  | { type: 'HYDRATE'; payload: Omit<FinanceState, 'isHydrated'> }
  | { type: 'SET_USER'; payload: Partial<User> }
  | { type: 'ADD_ENTITY'; payload: Omit<Entity, 'id' | 'createdAt'> }
  | { type: 'UPDATE_ENTITY'; payload: { id: string } & Partial<Entity> }
  | { type: 'DELETE_ENTITY'; payload: string }
  | { type: 'ADD_DEBT'; payload: Omit<Debt, 'id' | 'createdAt' | 'isRecurring'> }
  | { type: 'UPDATE_DEBT'; payload: { id: string } & Partial<Debt> }
  | { type: 'DELETE_DEBT'; payload: string }
  | { type: 'MARK_PAID'; payload: { debtId: string; installmentId?: string; dueDate?: string } }
  | { type: 'UNMARK_PAID'; payload: { installmentId: string } }
  | { type: 'ADD_GOAL'; payload: Omit<Goal, 'id' | 'createdAt'> }
  | { type: 'UPDATE_GOAL'; payload: { id: string } & Partial<Goal> }
  | { type: 'DELETE_GOAL'; payload: string }
  | { type: 'ADD_INCOME'; payload: Omit<Income, 'id' | 'createdAt'> }
  | { type: 'UPDATE_INCOME'; payload: { id: string } & Partial<Income> }
  | { type: 'DELETE_INCOME'; payload: string }
  | { type: 'SNOOZE_BILL'; payload: { billKey: string; until: string } }
  | { type: 'UNSNOOZE_BILL'; payload: { billKey: string } }
  | { type: 'ADD_ACCOUNT'; payload: Omit<Account, 'id' | 'createdAt'> }
  | { type: 'UPDATE_ACCOUNT'; payload: { id: string } & Partial<Account> }
  | { type: 'DELETE_ACCOUNT'; payload: string }
  | { type: 'ADD_RECURRING_INCOME'; payload: Omit<RecurringIncome, 'id' | 'createdAt'> }
  | { type: 'UPDATE_RECURRING_INCOME'; payload: { id: string } & Partial<RecurringIncome> }
  | { type: 'DELETE_RECURRING_INCOME'; payload: string }
  | { type: 'GENERATE_RECURRING_INCOMES' }
  | { type: 'ADD_TRANSFER'; payload: Omit<Transfer, 'id' | 'createdAt'> }
  | { type: 'DELETE_TRANSFER'; payload: string }
  | { type: 'ADD_BANK_CONNECTION'; payload: Omit<BankConnection, 'id' | 'createdAt'> }
  | { type: 'UPDATE_BANK_CONNECTION'; payload: { id: string } & Partial<BankConnection> }
  | { type: 'DELETE_BANK_CONNECTION'; payload: { id: string; purgeIncomes?: boolean } }
  | {
      type: 'IMPORT_PLUGGY_TRANSACTIONS';
      payload: { connectionId: string; incomes: Income[]; lastSyncAt: string };
    }
  | {
      /** Combined create-or-update for a Pluggy item: ensures the
       * BankConnection exists, materializes one Account per Pluggy
       * account (dedup by sourcePluggyAccountId), then attaches
       * transactions as Income rows pointing at those accounts. Replaces
       * 3 separate dispatches that had ordering / id-handoff issues. */
      type: 'IMPORT_PLUGGY_FULL';
      payload: {
        connection: Omit<BankConnection, 'id' | 'createdAt'> & {
          existingId?: string;
        };
        accounts: Array<{
          pluggyAccountId: string;
          name: string;
          type: AccountType;
          balance: number;
        }>;
        transactions: Array<{
          sourcePluggyId: string;
          pluggyAccountId: string;
          description: string;
          amount: number;
          date: string;
          direction: IncomeDirection;
        }>;
        syncedAt: string;
      };
    }
  /** Retroactive cleanup: removes Pluggy-imported Incomes whose
   * description matches the same-person-transfer heuristic (Cofrinho
   * aporte/resgate, pagamento de fatura, etc). Use when the user enabled
   * the filter on a DB that already has noise from a pre-filter import. */
  | { type: 'PURGE_PLUGGY_INTERNAL' }
  | { type: 'RESET_ALL' }
  | { type: 'IMPORT_DATA'; payload: Omit<FinanceState, 'isHydrated'> };

// Legacy data shape from vanilla JS version
export interface LegacyTransaction {
  id: string;
  name: string;
  tags: string[];
  direction: 'entrada' | 'saida';
  amount: number;
  dueDate: string;
  startDate?: string;
  endDate?: string;
  progress?: number;
}
